name: Main workflow

on: push

jobs:

  flake8-lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  pull-data:
    name: Pull data
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pull dataset
      - run: |
          pip install -r requirements.txt
          python src/pull_data.py
