name: Main workflow

on: push

jobs:

  flake8-lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: py-actions/flake8@v2

  prepare-data:
    name: Prepare (pull, process) data
    runs-on: ubuntu-latest

    steps:
      - name: Cache Hugging Face data
        id: cache-huggingface
        uses: actions/cache@v3
        with:
          path: |
            cache/huggingface
            data
          key: huggingface-cache
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Prepare dataset
        run: |
          pip install -r requirements.txt
          python src/pull_data.py
          python src/process_data.py
          python src/train_model.py

#  train-model:
#    name: Train model
#    runs-on: ubuntu-latest
#    needs: prepare-data
#
#    steps:
#      - name: Cache Hugging Face data
#        id: cache-huggingface
#        uses: actions/cache@v3
#        with:
#          path: |
#            cache/huggingface
#            data
#          key: huggingface-cache
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#      - name: Train
#        run: |
#          pip install -r requirements.txt
#          python src/train_model.py
