name: Main workflow

on: push

jobs:

  lint-flake:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
#      - name: Cache Python dependencies
#        uses: actions/cache@v3.2.4
#        id: python-cache
#        with:
#          path: ${{ env.pythonLocation }}
#          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
#      - name: Install pip dependencies
#        if: steps.python-cache.outputs.cache-hit != 'true'
#        run: pip install -r requirements.txt
      - name: Lint
        run: |
          python src/path.py
          flake8 src

#  prepare-data:
#    name: Prepare (pull, process) data
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Cache Hugging Face data
#        id: cache-huggingface
#        uses: actions/cache@v3
#        with:
#          path: |
#            cache/huggingface
#            data
#          key: huggingface-cache
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#      - name: Prepare dataset
#        run: |
#          pip install -r requirements.txt
#          python src/pull_data.py
#          python src/process_data.py
#          python src/train_model.py

#  train-model:
#    name: Train model
#    runs-on: ubuntu-latest
#    needs: prepare-data
#
#    steps:
#      - name: Cache Hugging Face data
#        id: cache-huggingface
#        uses: actions/cache@v3
#        with:
#          path: |
#            cache/huggingface
#            data
#          key: huggingface-cache
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#      - name: Train
#        run: |
#          pip install -r requirements.txt
#          python src/train_model.py
