name: Main workflow

on: push

jobs:

  lint-flake:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        id: python-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - if: steps.python-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - run: |
          python -c 'import spacy; print(spacy.__version__)'
          flake8 src

  prepare-data:
    name: Prepare (pull, process) data
    runs-on: ubuntu-latest
    needs: lint-flake

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/cache@v3
        id: python-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - if: steps.python-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - run: |
          python src/pull_data.py
          python src/process_data.py

      - uses: actions/cache@v3
        id: huggingface-cache
        with:
          path: |
            cache/huggingface
            data
          key: huggingface-cache-${{ hashFiles('cache/huggingface') }}-${{ hashFiles('data') }}

  train-model:
    name: Train model
    runs-on: ubuntu-latest
    needs: prepare-data

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/cache@v3
        id: python-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - if: steps.python-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - uses: actions/cache@v3
          id: huggingface-cache
          with:
            path: |
              cache/huggingface
              data
            key: huggingface-cache-${{ hashFiles('cache/huggingface') }}-${{ hashFiles('data') }}

      - run: python src/train_model.py

#    steps:
#      - name: Cache Hugging Face data
#        id: cache-huggingface
#        uses: actions/cache@v3
#        with:
#          path: |
#            cache/huggingface
#            data
#          key: huggingface-cache
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#      - name: Train
#        run: |
#          pip install -r requirements.txt
#          python src/train_model.py
