name: Test workflow

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'dev/**'
  pull_request:
    branches:
      - main

jobs:

  run-server:
    name: Run REST API
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#          architecture: 'x64'
      - uses: actions/cache@v3
        id: python-cache
        with:
          path: ${{ github.workspace }}
          key: ${{ github.workspace }}-${{ hashFiles('requirements-dev.txt') }}
      - if: steps.python-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements-dev.txt
      - uses: actions/cache@v3
        id: huggingface-cache
        with:
          path: ~/.cache/huggingface
          key: huggingface-cache
#      - name: Load the best model
#        uses: actions/download-artifact@v3
#        with:
#          name: huggingface-models-best-model
#          path: models
      - name: Deploy the best model
        run: |
          nohup python src/server.py > output.log &
